=== HericPospiecha/BryansCafe/menu.dtd
<!ELEMENT menu (meal*, beverages)>
<!ELEMENT meal (name, price, description, image)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

<!ELEMENT beverages (coffeeAndHotChocolates, otherBeverages)>
<!ELEMENT coffeeAndHotChocolates (variation*)>
<!ELEMENT variation (size, price, description)>
<!ELEMENT size (#PCDATA)>

<!ELEMENT otherBeverages (drink*)>
<!ELEMENT drink (name, price)>

=== HericPospiecha/BryansCafe/menu.xml
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
  <meal>
    <name>Beetroot and feta salad</name>
    <price>15.00</price>
    <description>Suitable for vegetarians, made with fresh beetroot.</description>
    <image>images/beetroot.jpeg</image>
  </meal>
  <meal>
    <name>Sourdough Rye Sandwich</name>
    <price>18.00</price>
    <description>Cheese and salad sandwich made with organic, sourdough rye bread.</description>
    <image>images/sandwich.jpeg</image>
  </meal>
  <meal>
    <name>Spinach Pie and Salad</name>
    <price>20.00</price>
    <description>Tasty pie with salad.</description>
    <image>images/spinach.jpeg</image>
  </meal>
  <meal>
    <name>Feta pancakes with salad</name>
    <price>19.50</price>
    <description>Tasty pancake filled with feta and salad.</description>
    <image>images/feta.jpeg</image>
  </meal>
  <beverages>
    <coffeeAndHotChocolates>
      <variation>
        <size>Small</size>
        <price>3.50</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
      </variation>
      <variation>
        <size>Regular</size>
        <price>4.00</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
      </variation>
      <variation>
        <size>Large</size>
        <price>4.50</price>
        <description>For coffee, please inform the staff of the coffee type.</description>
      </variation>
    </coffeeAndHotChocolates>
    <otherBeverages>
      <drink>
        <name>Bottled Water</name>
        <price>2.00</price>
      </drink>
      <drink>
        <name>Fresh Juice</name>
        <price>6.00</price>
      </drink>
      <drink>
        <name>Soda</name>
        <price>3.00</price>
      </drink>
    </otherBeverages>
  </beverages>
</menu>
